# Configuración de análisis de código para JUANIA
# Asegura código limpio y mantenible siguiendo las mejores prácticas

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Errores comunes
    - avoid_print
    - avoid_unnecessary_containers
    - avoid_web_libraries_in_flutter
    - no_logic_in_create_state
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - prefer_final_locals
    - unnecessary_const
    - unnecessary_new
    
    # Estilo y formato
    - always_declare_return_types
    - always_put_required_named_parameters_first
    - annotate_overrides
    - avoid_returning_null_for_void
    - camel_case_types
    - empty_catches
    - library_private_types_in_public_api
    - null_closures
    - prefer_single_quotes
    - sort_child_properties_last
    - use_key_in_widget_constructors
    
    # Performance
    - prefer_collection_literals
    - prefer_spread_collections
    - sized_box_for_whitespace
    
    # Documentación
    - comment_references

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated/**"
  
  errors:
    # Tratar como errores
    invalid_annotation_target: ignore
    
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
